import type { Theme } from './types'

export const themes: Record<string, Theme> = {
  classic: {
    id: 'classic',
    name: 'Класика',
    previewBg: 'bg-[#e2dfff]',
    vars: {
      '--lex-primary': '#3632b7',
      '--lex-primary-light': '#e2dfff',
      '--lex-secondary': '#855300',
      '--lex-secondary-light': '#ffddb8',
      '--lex-accent': '#fea619',
      '--lex-bg': '#faf9f8',
      '--lex-surface': '#ffffff',
      '--lex-card': '#f4f3f2',
      '--lex-text': '#1a1c1c',
      '--lex-muted': '#6b7280',
      '--lex-radius': '2rem',
      '--lex-radius-card': '2.5rem',
      '--lex-hero-grad': 'linear-gradient(to bottom right, #3632b7, #504ed0, #855300)',
      '--lex-cover-bg': '#12082e',
    },
  },
  magazine: {
    id: 'magazine',
    name: 'Списание',
    previewBg: 'bg-[#fff0e8]',
    vars: {
      '--lex-primary': '#c2410c',
      '--lex-primary-light': '#ffedd5',
      '--lex-secondary': '#1e3a5f',
      '--lex-secondary-light': '#dbeafe',
      '--lex-accent': '#f97316',
      '--lex-bg': '#fffbf5',
      '--lex-surface': '#ffffff',
      '--lex-card': '#f5f5f4',
      '--lex-text': '#111827',
      '--lex-muted': '#6b7280',
      '--lex-radius': '0.5rem',
      '--lex-radius-card': '0.75rem',
      '--lex-hero-grad': 'linear-gradient(to bottom right, #c2410c, #ea580c, #1e3a5f)',
      '--lex-cover-bg': '#1a0800',
    },
  },
  adventure: {
    id: 'adventure',
    name: 'Приключение',
    previewBg: 'bg-[#d1fae5]',
    vars: {
      '--lex-primary': '#065f46',
      '--lex-primary-light': '#d1fae5',
      '--lex-secondary': '#92400e',
      '--lex-secondary-light': '#fef3c7',
      '--lex-accent': '#34d399',
      '--lex-bg': '#f0fdf4',
      '--lex-surface': '#ffffff',
      '--lex-card': '#ecfdf5',
      '--lex-text': '#064e3b',
      '--lex-muted': '#6b7280',
      '--lex-radius': '1.5rem',
      '--lex-radius-card': '2rem',
      '--lex-hero-grad': 'linear-gradient(to bottom right, #065f46, #047857, #92400e)',
      '--lex-cover-bg': '#012a10',
    },
  },
  teens: {
    id: 'teens',
    name: 'Горен курс',
    previewBg: 'bg-[#e8eeff]',
    vars: {
      '--lex-primary': '#4C6EF5',
      '--lex-primary-light': '#e8eeff',
      '--lex-secondary': '#12B886',
      '--lex-secondary-light': '#e6fcf5',
      '--lex-accent': '#FCC419',
      '--lex-bg': '#F8F9FE',
      '--lex-surface': '#ffffff',
      '--lex-card': '#eef2ff',
      '--lex-text': '#1A1B2E',
      '--lex-muted': '#6b7280',
      '--lex-radius': '1rem',
      '--lex-radius-card': '1.5rem',
      '--lex-hero-grad': 'linear-gradient(to bottom right, #4C6EF5, #7950F2, #12B886)',
      '--lex-cover-bg': '#0f0f23',
    },
  },
  kindergarten: {
    id: 'kindergarten',
    name: 'Детска градина',
    previewBg: 'bg-[#fff3e0]',
    vars: {
      '--lex-primary': '#FF7043',
      '--lex-primary-light': '#ffe0d6',
      '--lex-secondary': '#29B6F6',
      '--lex-secondary-light': '#e1f5fe',
      '--lex-accent': '#FFD740',
      '--lex-bg': '#fffbf5',
      '--lex-surface': '#ffffff',
      '--lex-card': '#fff3e0',
      '--lex-text': '#3e2723',
      '--lex-muted': '#8d6e63',
      '--lex-radius': '2.5rem',
      '--lex-radius-card': '3rem',
      '--lex-hero-grad': 'linear-gradient(to bottom right, #FF7043, #FFA726, #29B6F6)',
      '--lex-cover-bg': '#1a0800',
    },
  },

  levski: {
    id: 'levski',
    name: 'Левски София',
    previewBg: 'bg-[#d0daf7]',
    vars: {
      '--lex-primary': '#1A3D8F',
      '--lex-primary-light': '#d0daf7',
      '--lex-secondary': '#c8a020',
      '--lex-secondary-light': '#fef3c7',
      '--lex-accent': '#FFD700',
      '--lex-bg': '#f4f7fe',
      '--lex-surface': '#ffffff',
      '--lex-card': '#eef2fb',
      '--lex-text': '#0e1e3d',
      '--lex-muted': '#5a6e9c',
      '--lex-radius': '1.5rem',
      '--lex-radius-card': '2rem',
      '--lex-hero-grad': 'linear-gradient(135deg, #0e1e3d 0%, #1A3D8F 50%, #2952B3 100%)',
      '--lex-cover-bg': '#04102b',
    },
  },
}

export const defaultTheme = themes.classic
