import type { Theme } from './types'

export const themes: Record<string, Theme> = {
  classic: {
    id: 'classic',
    name: 'Класика',
    previewBg: 'bg-[#e2dfff]',
    vars: {
      '--lex-primary': '#3632b7',
      '--lex-primary-light': '#e2dfff',
      '--lex-secondary': '#855300',
      '--lex-secondary-light': '#ffddb8',
      '--lex-accent': '#fea619',
      '--lex-bg': '#faf9f8',
      '--lex-surface': '#ffffff',
      '--lex-card': '#f4f3f2',
      '--lex-text': '#1a1c1c',
      '--lex-muted': '#6b7280',
      '--lex-radius': '2rem',
      '--lex-radius-card': '2.5rem',
      '--lex-hero-grad': 'linear-gradient(to bottom right, #3632b7, #504ed0, #855300)',
    },
  },
  magazine: {
    id: 'magazine',
    name: 'Списание',
    previewBg: 'bg-[#fff0e8]',
    vars: {
      '--lex-primary': '#c2410c',
      '--lex-primary-light': '#ffedd5',
      '--lex-secondary': '#1e3a5f',
      '--lex-secondary-light': '#dbeafe',
      '--lex-accent': '#f97316',
      '--lex-bg': '#fffbf5',
      '--lex-surface': '#ffffff',
      '--lex-card': '#f5f5f4',
      '--lex-text': '#111827',
      '--lex-muted': '#6b7280',
      '--lex-radius': '0.5rem',
      '--lex-radius-card': '0.75rem',
      '--lex-hero-grad': 'linear-gradient(to bottom right, #c2410c, #ea580c, #1e3a5f)',
    },
  },
  adventure: {
    id: 'adventure',
    name: 'Приключение',
    previewBg: 'bg-[#d1fae5]',
    vars: {
      '--lex-primary': '#065f46',
      '--lex-primary-light': '#d1fae5',
      '--lex-secondary': '#92400e',
      '--lex-secondary-light': '#fef3c7',
      '--lex-accent': '#34d399',
      '--lex-bg': '#f0fdf4',
      '--lex-surface': '#ffffff',
      '--lex-card': '#ecfdf5',
      '--lex-text': '#064e3b',
      '--lex-muted': '#6b7280',
      '--lex-radius': '1.5rem',
      '--lex-radius-card': '2rem',
      '--lex-hero-grad': 'linear-gradient(to bottom right, #065f46, #047857, #92400e)',
    },
  },
}

export const defaultTheme = themes.classic
